version: 2.1

jobs:
  run_ray_example:
    docker:
      - image: gueraf/rules_ray_py_test:latest
    steps:
      - run:
          name: "examples/py_ray_hello_world:hello_world_ray_job"
          command: |
            git clone --recurse-submodules https://github.com/gueraf/rules_ray_py_test.git && \
            cd rules_ray_py_test/ && \
            timeout 5m bazelisk run examples/py_ray_hello_world:hello_world_ray_job -- --wait

workflows:
  version: 2
  main:
    jobs:
      - run_ray_example